### ISSUE TITLE
What is the `bbox` folder supposed to contain for crosstask dataset?

### ISSUE THREAD

**Issue by dhruvdcoder** [Jiankai-Sun/plate-ral#2]
Hi! Thanks for providing the code for your paper. I was trying to run the code after downloading the crosstask dataset. However, I did not find any folder called `bbox_v0` or `bbox` in the dataset. May I know how I could get this folder? I tried looking at the comments in the code as well as the paper itself but I could not find any mention of such a folder. Any help in this regard would be greatly appreciated.

**Comment by Jiankai-Sun** [comment]
Hi, @dhruvdcoder,

Thank you for your interest in our work.

Previously we explored using the 2D bounding box (`bbox` or `bbox_v0`) obtained by Faster RCNN as one of the inputs. However, in the final version, we did not use `bbox` as an input so you do not need to care about `bbox`. I've updated the code and remove the `bbox`-related content,

**Comment by dhruvdcoder** [comment]
Sounds good. Thanks for the quick response.
